#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
( cat <<_USER_\SCRIPT_
#!/bin/bash
# sets the queue
#BSUB -q 8nm

echo 'environment:'
echo
env
ulimit -v 3000000
echo 'copying job dir to worker'
cd $CMSSW_BASE/src
eval `scramv1 ru -sh`
cd -
cp -rf $LS_SUBCWD .
ls
cd `find . -type d | grep /`
echo 'running'
cmsRun run_cfg.py
if [ $? != 0 ]; then
    echo wrong exit code! removing all root files
    rm *.root
    exit 1 
fi
echo 'sending the job directory back'

for file in *.root; do
newFileName=`echo $file | sed -r -e 's/\./_5\./'`
fullFileName=/store/cmst3/user/manzoni/CMG/SUSYBBHToTauTau_M-450_8TeV-pythia6-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/PAT_CMG_V5_16_0/HTT_24Jul_newTES_manzoni_Up/$newFileName
#this does cmsStage, but with retries
cmsStageWithFailover.py -f $file $fullFileName
#write the files as user readable but not writable
eos chmod 755 /eos/cms/$fullFileName
done
rm *.root
cp -rf * $LS_SUBCWD

_USER_SCRIPT_
) > $LSB_CHKFILENAME.shell
chmod u+x $LSB_CHKFILENAME.shell
/usr/local/lsf/etc/job_starter '$LSB_JOBFILENAME.shell'
saveExit=$?
/bin/rm -f $LSB_JOBFILENAME.shell
(exit $saveExit)

ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
